{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "outpost.fullname" . }}-pod-manager
  labels:
    {{- include "outpost.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "pods/status", "namespaces", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "outpost.fullname" . }}-pod-manager-binding
  labels:
    {{- include "outpost.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "outpost.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "outpost.fullname" . }}-pod-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}
